version: '3.6'
services:
  aurahsi:
    image: ghcr.io/laggykiller/aurahsi:latest # Comment out for building locally
    # image: aurahsi # Uncomment for building locally
    # build: . # Uncomment for building locally
    volumes:
      - ./app.py:/app/app.py
      - ./assets:/app/assets
      - /dev/shm:/dev/shm
    environment:
      - TZ=Asia/Hong_Kong
    restart: unless-stopped
    ports:
      - 8080:80